import { poppins } from "@/fonts/fonts";
import "./globals.css";

export const metadata = {
  title: "Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>{children}</body>
    </html>
  );
}
